kind = "mobile"
previewPath = "/"
title = "MediKit"
version = "1.0.0"
id = "artifacts/medic-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21234

[services.development]
run = "pnpm --filter @workspace/medic-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/medic-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/medic-app", "run", "serve" ]

[services.env]
PORT = "21234"
BASE_PATH = "/"
